# Generated by Django 4.2.1 on 2023-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongle',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('serien_nr', models.CharField(db_column='Serien-Nr', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('gueltig_von', models.DateField(blank=True, db_column='Gueltig von', null=True)),
                ('gueltig_bis', models.DateField(blank=True, db_column='Gueltig bis', null=True)),
                ('projekt_produkt', models.CharField(db_column='Projekt/Produkt', max_length=45)),
                ('kunde', models.CharField(db_column='Kunde', max_length=45)),
                ('standort', models.CharField(db_column='Standort', max_length=45)),
                ('haendler', models.CharField(blank=True, db_column='Haendler', max_length=45, null=True)),
                ('datum_letzte_aenderung', models.DateField(db_column='Datum letzte Aenderung')),
                ('datum_erstausgabe', models.DateField(db_column='Datum Erstausgabe')),
                ('firmcode', models.CharField(db_column='Firmcode', max_length=45)),
            ],
            options={
                'db_table': 'dongle',
            },
        ),
    ]
