# Generated by Django 4.2.1 on 2023-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lizenz',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('productcode', models.IntegerField(db_column='ProductCode')),
                ('lizenzname', models.CharField(db_column='LizenzName', max_length=45)),
                ('einheiten', models.IntegerField(blank=True, db_column='Einheiten', null=True)),
                ('gueltig_von', models.DateField(db_column='Gueltig von')),
                ('ablaufdatum', models.DateField(db_column='Ablaufdatum')),
                ('lizenzanzahl', models.IntegerField(db_column='LizenzAnzahl')),
                ('mitarbeiter', models.CharField(db_column='Mitarbeiter', max_length=45)),
                ('projekt', models.CharField(db_column='Projekt', max_length=45)),
                ('dognle_lfd_nr_field', models.IntegerField(db_column='Dognle_Lfd. Nr.')),
            ],
            options={
                'db_table': 'lizenz',
                'managed': False,
            },
        ),
    ]
