# Generated by Django 4.2.1 on 2023-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongle',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('serien_nr', models.CharField(db_column='Serien-Nr', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('gueltig_von', models.DateField(db_column='Gueltig von')),
                ('gueltig_bis', models.DateField(db_column='Gueltig bis')),
                ('projekt_produkt', models.CharField(db_column='Projekt/Produkt', max_length=45)),
                ('standort', models.CharField(db_column='Standort', max_length=45)),
                ('haendler', models.CharField(db_column='Haendler', max_length=45)),
                ('datum_letzte_õnderung', models.DateField(db_column='Datum letzte ─nderung')),
                ('datum_erstausgabe', models.DateField(db_column='Datum Erstausgabe')),
                ('benutzer_firmcode', models.IntegerField(db_column='Benutzer_Firmcode')),
            ],
            options={
                'db_table': 'dongle',
                'managed': False,
            },
        ),
    ]
