# Generated by Django 4.2.1 on 2023-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongle',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('serien_nr', models.CharField(db_column='Serien-Nr', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('gueltig_von', models.DateField(blank=True, db_column='Gueltig von', null=True)),
                ('gueltig_bis', models.DateField(blank=True, db_column='Gueltig bis', null=True)),
                ('projekt_produkt', models.CharField(db_column='Projekt/Produkt', max_length=45)),
                ('kunde', models.CharField(db_column='Kunde', max_length=45)),
                ('standort', models.CharField(db_column='Standort', max_length=45)),
                ('haendler', models.CharField(blank=True, db_column='Haendler', max_length=45, null=True)),
                ('datum_letzte_aenderung', models.DateField(db_column='Datum letzte Aenderung')),
                ('datum_erstausgabe', models.DateField(db_column='Datum Erstausgabe')),
                ('firmcode', models.CharField(db_column='Firmcode', max_length=45)),
            ],
            options={
                'db_table': 'dongle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lizenz',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('firmcode', models.CharField(db_column='FirmCode', max_length=45)),
                ('productcode', models.IntegerField(db_column='ProductCode')),
                ('lizenzname', models.CharField(db_column='LizenzName', max_length=45)),
                ('einheiten', models.IntegerField(blank=True, db_column='Einheiten', null=True)),
                ('gueltig_von', models.DateField(db_column='Gueltig von')),
                ('gueltig_bis', models.DateField(blank=True, db_column='Gueltig bis', null=True)),
                ('lizenzanzahl', models.IntegerField(blank=True, db_column='LizenzAnzahl', null=True)),
                ('mitarbeiter', models.CharField(db_column='Mitarbeiter', max_length=45)),
                ('projekt', models.CharField(db_column='Projekt', max_length=45)),
                ('kunde', models.CharField(db_column='Kunde', max_length=45)),
                ('dongle_serien_nr', models.CharField(blank=True, db_column='Dongle_Serien-Nr', max_length=45, null=True)),
            ],
            options={
                'db_table': 'lizenz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLogginCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('firm_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_loggin_customuser',
                'managed': False,
            },
        ),
    ]
