# Generated by Django 4.2.1 on 2023-07-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LizenzAnfordern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lizenz',
            fields=[
                ('lfd_nr_field', models.IntegerField(db_column='Lfd. Nr.', primary_key=True, serialize=False)),
                ('firmcode', models.CharField(db_column='FirmCode', max_length=45)),
                ('productcode', models.IntegerField(db_column='ProductCode')),
                ('lizenzname', models.CharField(db_column='LizenzName', max_length=45)),
                ('einheiten', models.IntegerField(blank=True, db_column='Einheiten', null=True)),
                ('gueltig_von', models.DateField(db_column='Gueltig von')),
                ('gueltig_bis', models.DateField(blank=True, db_column='Gueltig bis', null=True)),
                ('lizenzanzahl', models.IntegerField(blank=True, db_column='LizenzAnzahl', null=True)),
                ('mitarbeiter', models.CharField(db_column='Mitarbeiter', max_length=45)),
                ('projekt', models.CharField(db_column='Projekt', max_length=45)),
                ('kunde', models.CharField(db_column='Kunde', max_length=45)),
                ('dongle_serien_nr', models.CharField(blank=True, db_column='Dongle_Serien-Nr', max_length=45, null=True)),
            ],
            options={
                'db_table': 'lizenz',
                'managed': False,
            },
        ),
    ]
