# Generated by Django 4.2.1 on 2023-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benachrichtigung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogginCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('firm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField()),
                ('is_staff', models.IntegerField()),
            ],
            options={
                'db_table': 'user_loggin_customuser',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Kunde',
        ),
    ]
