# Generated by Django 4.2.1 on 2023-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.IntegerField(db_column='ID_Ticket', primary_key=True, serialize=False)),
                ('titel', models.CharField(db_column='Titel', max_length=45)),
                ('beschreibung', models.CharField(db_column='Beschreibung', max_length=45)),
                ('status', models.CharField(db_column='Status', max_length=45)),
                ('erstellungsdatum', models.DateField(db_column='Erstellungsdatum')),
                ('schliessungsdatum', models.DateField(blank=True, db_column='Schliessungsdatum', null=True)),
                ('admin_verwalter_id', models.IntegerField(blank=True, db_column='Admin/Verwalter_ID', null=True)),
                ('dongle_seriennumemr', models.CharField(blank=True, db_column='Dongle_seriennumemr', max_length=45, null=True)),
                ('lizenzname', models.CharField(blank=True, db_column='LizenzName', max_length=45, null=True)),
                ('grund_der_ablehnung', models.CharField(blank=True, db_column='Grund_der_Ablehnung', max_length=45, null=True)),
                ('kunde', models.CharField(db_column='Kunde', max_length=45)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
