# Generated by Django 4.2.1 on 2023-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('firm_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_login_customuser',
                'managed': False,
            },
        ),
    ]
