# Generated by Django 4.2.1 on 2023-06-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminseite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='user_loggin_customuser',
        ),
    ]
