# Generated by Django 4.2.1 on 2023-07-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminseite', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
