# Generated by Django 4.2.1 on 2023-06-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_loggin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False, 'permissions': [('can_view_user', 'Can view user')]},
        ),
    ]
