# Generated by Django 4.2.1 on 2023-06-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_loggin', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='user_loggin_customuser',
        ),
    ]
